declare module 'vtex.styleguide' {
  export const Alert
  export const Button
  export const PageBlock
  export const Layout
  export const PageHeader
  export const Card
  export const Checkbox
  export const Tab
  export const Tabs
  export const Tag
  export const ButtonWithIcon
  export const ButtonPlain
  export const IconDownload
  export const IconDelete
  export const IconEdit
  export const IconExternalLinkMini
  export const ToastProvider
  export const withToast
  export const Box
  export const LineChart
  export const Toggle
  export const Table
  export const IconArrowUp
  export const IconArrowDown
  export const IconWarning
  export const IconClose
  export const Spinner
  export const Tooltip
  export const InputSearch
  export const Input
  export const Modal
  export const FilterBar
  export const IconClear
  export const IconSearch
  export const IconFailure
  export const Divider
  export const DatePicker
  export const Dropdown
  export const TimePicker
  // eslint-disable-next-line @typescript-eslint/naming-convention
  export const EXPERIMENTAL_Select
  // eslint-disable-next-line @typescript-eslint/naming-convention
  export const EXPERIMENTAL_useCheckboxTree
  // eslint-disable-next-line @typescript-eslint/naming-convention
  export const EXPERIMENTAL_useTableMeasures
  // eslint-disable-next-line @typescript-eslint/naming-convention
  export const EXPERIMENTAL_useTableProportion
}
