query listSupplyLots($skuId: ID!, $warehouseId: ID!, $supplyLotId: ID) {
  listSupplyLots(skuId: $skuId, warehouseId: $warehouseId, supplyLotId: $supplyLotId) {
    supplyLotId
    skuId
    warehouseId
    totalQuantity
    dateOfSupplyUtc
    keepSellingAfterExpiration
  }
}
